apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acm-ci-pipeline
spec:
  description: |
    The ACM CI pipeline that has the ACM components tests 
  params:
    - description: 'Hub OCP API url'
      name: OCP_HUB_CLUSTER_API_URL
      default: 'https://api.qe3-vmware-ibm.dev09.red-chesterfield.com:6443'
      type: string
    - description: 'Hub OCP username'
      name: OCP_HUB_CLUSTER_USER
      default: 'kubeadmin'
      type: string
    - description: 'Hub OCP password'
      name: OCP_HUB_CLUSTER_PASSWORD
      default: 'm35Ji-rEbmC-XB4po-fM2hP'
      type: string
    - description: 'Release branch'
      name: RELEASE_BRANCH
      default: 'main'
      type: string
  tasks:
    - name: fetch-clusters
      taskRef:
        name: fetch-clusters-task
      params:
        - name: OCP_HUB_CLUSTER_API_URL
          value: $(params.OCP_HUB_CLUSTER_API_URL)
        - name: OCP_HUB_CLUSTER_USER
          value: $(params.OCP_HUB_CLUSTER_USER)
        - name: OCP_HUB_CLUSTER_PASSWORD
          value: $(params.OCP_HUB_CLUSTER_PASSWORD)
    - name: clc-non-ui-tests
      taskRef:
        name: clc-non-ui-tests-task
      params:
        - name: OCP_HUB_CLUSTER_API_URL
          value: $(params.OCP_HUB_CLUSTER_API_URL)
        - name: OCP_HUB_CLUSTER_USER
          value: $(params.OCP_HUB_CLUSTER_USER)
        - name: OCP_HUB_CLUSTER_PASSWORD
          value: $(params.OCP_HUB_CLUSTER_PASSWORD)
        - name: RELEASE_BRANCH
          value: $(params.RELEASE_BRANCH) 