apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-clusters-task
spec:
  description: |
    Fetch provisoned managed clusters info that are in ready state
  params:
    - description: 'Hub OCP API url'
      name: HUB_OCP_API_URL
      default: 'https://api.qe3-vmware-ibm.dev09.red-chesterfield.com:6443'
      type: string
    - description: 'Hub OCP username'
      name: HUB_OCP_USERNAME
      default: 'kubeadmin'
      type: string
    - description: 'Hub OCP password'
      name: HUB_OCP_PASSWORD
      default: 'm35Ji-rEbmC-XB4po-fM2hP'
      type: string
  steps:
  - image: quay.io/vboulos/acmqe-automation/fetch-managed-clusters:fetch-v.1.0
    imagePullPolicy: Always
    env:
    - name: HUB_OCP_API_URL
      value: $(params.HUB_OCP_API_URL)
    - name: HUB_OCP_USERNAME
      value: $(params.HUB_OCP_USERNAME)
    - name: HUB_OCP_PASSWORD
      value: $(params.HUB_OCP_PASSWORD)
    script: |
      cd fetch-clusters
      ls -al
      ./fetch_clusters_commands.sh
      ls -al