---
  # NPM GROOVY LINT (+ Format & Auto-fix) 
  # https://www.npmjs.com/package/npm-groovy-lint 
  
  name: groovy file lint
  
  on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'
  
  jobs:
    build:
      # Name the Job
      name: groovy file lint
      # Set the agent to run on
      runs-on: ubuntu-latest
  
      ############################################
      # Grant status permission for MULTI_STATUS #
      ############################################
      permissions:
        contents: read
        packages: read
        statuses: write
  
      ##################
      # Load all steps #
      ##################
      steps:
      ##########################
      # Checkout the code base #
      ##########################
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        ################################
        # Run Linter against code base #
        ################################
        - name: groovy file lint 
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: |
            npm install -g npm-groovy-lint 
            npm-groovy-lint --failon error ci/jenkinsfiles/vars/*.groovy --loglevel warning
            npm-groovy-lint --failon error ci/jenkinsfiles/*.jenkinsfiles
            